//// ****** THIS FILE IS AUTOGENERATED ******
//// //          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.868531
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

#include "step_motor.h"

#define NUM_LEDS 7

const int led_pins[NUM_LEDS] = {2, 3, 4, 5, 6, 7, 10};

void user_setup();
void user_loop();

int call_INITIALIZE(); 
int call_FINALIZE(); 
float get_THETA(); 
int set_THETA(float); 
int set_STEP(int);
int call_TurnOffLEDs();
int set_LED(int);

#endif // inodriver_user_h
