//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.868531
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

#include "shutter.h"
#include "step_motor.h"
#include "wheel.h"
#include "temperature.h"

void user_setup();
void user_loop();

int call_INITIALIZE(); 
int call_FINALIZE(); 
int get_POW(int); 
int set_POW(int, int); 
float get_SETPOINT(); 
int set_SETPOINT(float); 
float get_THETA(); 
int set_THETA(float); 
int get_TEMPCTRL(); 
int set_TEMPCTRL(int); 
int get_FW(int); 
int set_FW(int, int); 
int get_SHUT(int); 
int set_SHUT(int, int); 
float get_TEMP(); 


#endif // inodriver_user_h