//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.868531
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////



#include "inodriver_user.h"

#define MIN_PIN 9
#define MAX_PIN 13



void user_setup() {
}

void user_loop() {
}


void turn_off_LEDS(){
  for (int i=MIN_PIN; i < MAX_PIN + 1; i++){
    digitalWrite(i, LOW);
  }
  return 0;
}

int set_LED(int value) {  
  turn_off_LEDS();
  digitalWrite(value, HIGH);
  return 0;
}


