//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.868531
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////



#include "inodriver_user.h"
#include <Arduino.h>

void user_setup() {
  for (int i=0; i < NUM_LEDS; i++){ // EN REALIDAD ESTO ESTA MAL
    pinMode(led_pins[i], OUTPUT);
  }
}

void user_loop() {
}


int turn_off_LEDS(){
  for (int i=0; i < NUM_LEDS; i++) {
    digitalWrite(i, LOW);
  }
  return 0;
}

int set_LED(int pin) {  
  turn_off_LEDS();
  digitalWrite(pin, HIGH);
  return 0;
}
