//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; D:\Bruno\Codigo\new_spim\spim\spim\drivers\arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-17T11:57:05.596713
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////



// Import libraries
#include <Arduino.h>

#include "inodriver_bridge.h"
#include "inodriver_user.h"

#define BAUD_RATE 115200

void setup() {
  bridge_setup();
  
  user_setup();

  Serial.begin(BAUD_RATE);
  Serial.write("Chanoscopio");
}

void loop() {
  
  bridge_loop();
  
  user_loop();
}
