//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.867609
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_bridge_h
#define inodriver_bridge_h

#include <Arduino.h>

#include "SerialCommand.h"

#include "inodriver_user.h"

const char COMPILE_DATE_TIME[] = __DATE__ " " __TIME__;

void ok();
void error(const char*);
void error_i(int);
void bridge_loop();
void bridge_setup();

void getInfo();
void unrecognized(const char *);
void wrapperCall_INITIALIZE(); 
void wrapperCall_FINALIZE(); 
void wrapperGet_POW(); 
void wrapperSet_POW(); 
void wrapperGet_SETPOINT(); 
void wrapperSet_SETPOINT(); 
void wrapperGet_THETA(); 
void wrapperSet_THETA(); 
void wrapperGet_TEMPCTRL(); 
void wrapperSet_TEMPCTRL(); 
void wrapperGet_FW(); 
void wrapperSet_FW(); 
void wrapperGet_SHUT(); 
void wrapperSet_SHUT(); 
void wrapperGet_TEMP(); 


#endif // inodriver_bridge_h